# Generated by Django 5.1 on 2024-08-18 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_negocio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_negociada', models.IntegerField(help_text='Quantidade de ativos negociados')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliar_investidor.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroTunel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=3, max_digits=10)),
                ('periodicidade', models.IntegerField(help_text='Periodicidade em minutos')),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auxiliar_investidor.ativo')),
            ],
        ),
    ]
