# Generated by Django 5.1 on 2024-08-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliar_investidor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametroTunel',
            new_name='TunelParametro',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='nome',
            field=models.CharField(max_length=128),
        ),
    ]
