# Generated by Django 5.1 on 2024-08-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliar_investidor', '0002_rename_parametrotunel_tunelparametro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='quantidade_negociada',
        ),
    ]
