# Generated by Django 5.1 on 2024-08-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliar_investidor', '0004_tunelparametro_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='preco_negocio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunelparametro',
            name='email',
            field=models.EmailField(help_text='Informe seu e-mail para receber alertas', max_length=254),
        ),
        migrations.AlterField(
            model_name='tunelparametro',
            name='limite_inferior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunelparametro',
            name='limite_superior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
